name: Build Android
run-name: Build Android

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  Build_Android:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get

      - run: flutter build apk --release --split-per-abi

      - name: Rename APKs for each ABI
        run: |
          mv build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk build/app/outputs/flutter-apk/PicaComic-armeabi-v7a.apk
          mv build/app/outputs/flutter-apk/app-arm64-v8a-release.apk build/app/outputs/flutter-apk/PicaComic-arm64-v8a.apk
          mv build/app/outputs/flutter-apk/app-x86-release.apk build/app/outputs/flutter-apk/PicaComic-x86.apk
          mv build/app/outputs/flutter-apk/app-x86_64-release.apk build/app/outputs/flutter-apk/PicaComic-x86_64.apk
          mv build/app/outputs/flutter-apk/app-universal-release.apk build/app/outputs/flutter-apk/PicaComic-universal.apk

      - name: Upload armeabi-v7a APK
        uses: actions/upload-artifact@v4
        with:
          name: PicaComic-armeabi-v7a.apk
          path: build/app/outputs/flutter-apk/PicaComic-armeabi-v7a.apk

      - name: Upload arm64-v8a APK
        uses: actions/upload-artifact@v4
        with:
          name: PicaComic-arm64-v8a.apk
          path: build/app/outputs/flutter-apk/PicaComic-arm64-v8a.apk

      - name: Upload x86 APK
        uses: actions/upload-artifact@v4
        with:
          name: PicaComic-x86.apk
          path: build/app/outputs/flutter-apk/PicaComic-x86.apk

      - name: Upload x86_64 APK
        uses: actions/upload-artifact@v4
        with:
          name: PicaComic-x86_64.apk
          path: build/app/outputs/flutter-apk/PicaComic-x86_64.apk

      - run: flutter build appbundle --release

      - name: Rename APKs for each ABI
        run: mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/PicaComic-release.aab

      - uses: actions/upload-artifact@v4
        with:
          name: PicaComic-release.aab
          path: build/app/outputs/bundle/release/PicaComic-release.aab
