name: Build Linux
run-name: Build Linux
on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
jobs:
  Build_Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev webkit2gtk-4.1
          dart pub global activate flutter_to_debian
      - run: python3 debian/build.py
      - run: dart run flutter_to_arch
      - run: |
          sudo rm -rf build/linux/arch/app.tar.gz
          sudo rm -rf build/linux/arch/pkg
          sudo rm -rf build/linux/arch/src
          sudo rm -rf build/linux/arch/PKGBUILD
      - uses: actions/upload-artifact@v4
        with:
          name: deb_build
          path: build/linux/x64/release/debian
      - uses: actions/upload-artifact@v4
        with:
          name: arch_build
          path: build/linux/arch/